### ISSUE TITLE
have an error 

### ISSUE THREAD

**Issue by Arandompersonne** [oishikm12/PI-BOT#1]
Hello i have this error : 
Process uncaughtException: body is not defined
 Stack: ReferenceError: body is not defined
    at callback (/bots/Vegeta2/backpack.js:554:29)
    at giveResults (/bots/Vegeta2/node_modules/cloudscraper/index.js:244:5)
    at Request._callback (/bots/Vegeta2/node_modules/cloudscraper/index.js:109:7)
    at Request.self.callback (/bots/Vegeta2/node_modules/cloudscraper/node_modules/request/request.js:186:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/bots/Vegeta2/node_modules/cloudscraper/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/bots/Vegeta2/node_modules/cloudscraper/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
Can you help me ?

**Comment by oishikm12** [comment]
When did this error occur ? while running which script ? setup, pi or heartbeat
Also do this "npm install tf2". i recently updated this

**Comment by Arandompersonne** [comment]
When i launch pi :/

**Comment by Arandompersonne** [comment]
i just made a mistake, ty for fast reply

**Comment by oishikm12** [comment]
So is it working alri8 ? im new to this , would appreciate your feedback.
ps- close the issue if its fixed

**Comment by Arandompersonne** [comment]
idk if is this but it's working

**Comment by Arandompersonne** [comment]
the error return :/

**Comment by Arandompersonne** [comment]
if you see this add me on steam : Enzotoy #QLF
